version: 2

aliases:
  - &restore_build_cache
    keys:
      - discretemathematics-build-{{ .Branch }}-{{ .Revision }}
  - &restore_mint_cache
    keys:
      - discretemathematics-mint-{{ checksum "Mintfile" }}

defaults: &defaults
  docker:
    - image: cszatma/swift:5.0
  working_directory: ~/DiscreteMathematics

jobs:
  build-dev:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build package in debug mode.
          command: swift build
      - save_cache:
          key: discretemathematics-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - .build/
  build-release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build package in release mode.
          command: swift build -c release
  install-tools:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_mint_cache
      - run:
          name: Install tools with mint.
          command: make mint
      - save_cache:
          key: discretemathematics-mint-{{ checksum "Mintfile" }}
          paths:
            - /usr/local/lib/mint
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_mint_cache
      - run:
          name: Run swiftlint.
          command: make lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_build_cache
      - run:
          name: Run tests.
          command: swift test

workflows:
  build-test:
    jobs:
      - build-dev
      - build-release
      - install-tools
      - lint:
          requires:
            - install-tools
      - test:
          requires:
            - build-dev
